### ISSUE TITLE
.gitignore does not ignore /artifacts 

### ISSUE THREAD

**Issue by dokwon** [Anchor-Protocol/money-market-contracts#28]
The ./artifacts folder contains build outputs such as .wasm files, and should be added to the .gitignore

Any reason not to do this?

**Comment by MSNTCS** [comment]
The reason why we do not include it in `.gitigmore` is as follows: 
- Integrity checking: currently there is no mechanism on-chain for users to check the integrity of the deployed version of the contract with the codebase.
- Version controlling: We do not have a standard way of version control in the current state of contracts. We are coming up with a new standard way of version control on-chain and we will introduce it soon. 
- A production-ready output: we use a production-ready output for the team members to use across the team for integration tests.
