### ISSUE TITLE
[BUG] Initate Instance fail

### ISSUE THREAD

**Issue by ChunHuCui** [Anchor-Protocol/money-market-contracts#52]
**Describe the bug**
Initate Instance fail
I got a fail on init instance of the anchor money market contracts.
**To Reproduce**
id: 18465
{
  "owner_addr": "terra1tt3yrvuc7aq4lnyl0rykz97vvz8j6jhrv6qa99", 
  "stable_denom": "uusd",
  "aterra_code_id": 5, 
  "anc_emission_rate": "0.05", 
  "max_borrow_factor": "0.95" 
}
and 1 UST to deposit.

**Context & versions**
the latest code
![image](https://user-images.githubusercontent.com/68866354/140719116-093a4182-e13c-4987-b751-54287a2ae22e.png)

**(if applicable) suggested solution**

**Comment by MSNTCS** [comment]
Hello there, can I have the raw transaction?

**Comment by ChunHuCui** [comment]
![image](https://user-images.githubusercontent.com/68866354/141088500-f28b0ac6-324e-4fc5-acee-1bb87238cc49.png)
![image](https://user-images.githubusercontent.com/68866354/141088519-3f9d2cb5-7e3f-40c5-8294-5e19c418bf00.png)
I met the other error now.
now the terra is stable now?

**Comment by MSNTCS** [comment]
It is not a bug, here is the successful init on Bombay. https://finder.terra.money/bombay-12/tx/F6DEDB44BA93A3E74D2B0D20EBBA3C49465555E789E053C0E2E4962D6D6DE373.

 if you are instantiating on Bombay, please use the `1572` for `aterra_code_id`, 5 code_id is not cw20 contract for instantiation. That's why you got Null.

**Comment by ChunHuCui** [comment]
Yeah. I changed it to 1572, and got a fail on the creation of the contracts. the fee calculation has potential problems, it seems.

**Comment by MSNTCS** [comment]
Please increase the gas and follow the example I provide. I recommend terra.js for this.

**Comment by MSNTCS** [comment]
@ChunHuCui can I close this issue?

**Comment by ChunHuCui** [comment]
How can I increase the gas fee on terra station, and Can I create the terra.js to create the smart contracts?

**Comment by ChunHuCui** [comment]
Could you possibly share the terra.js code to create the contracts?

**Comment by ChunHuCui** [comment]
1.  I tried to deposit UST to terra1z6hzu4fs9fhtfk02eev6eq42xwuct4u5ejhq8s which is you deployed, but got a fail.
![image](https://user-images.githubusercontent.com/68866354/141169467-9d95ad4d-4e94-4134-b109-b9cda8bf47a0.png)

2.  I tried to deposit UST to terra15dwd5mj8v59wpj0wvt233mf5efdff808c5tkal which is described on anchorcliTestnet.json ("mmMarket": "terra15dwd5mj8v59wpj0wvt233mf5efdff808c5tkal"), got a success.
![image](https://user-images.githubusercontent.com/68866354/141169370-4f24c352-dbc3-4f29-829d-44c541ff805b.png)

I think the latest money market contracts have some potential problems now.
Could you possibly check the latest code and test it?
Thank you.

**Comment by MSNTCS** [comment]
we have a post_init step that I did not take for the example that I provide. https://github.com/Anchor-Protocol/money-market-contracts/blob/d2c5d089e1a34735e9483f9e54afb647bb00c13d/packages/moneymarket/src/market.rs#L31. I did not do that for that example, but you can try it yourself. after that step, you can use the contract.

**Comment by ChunHuCui** [comment]
Yeah. got a success.
thank you @MSNTCS .
