### ISSUE TITLE
Please publish v0.3.1

### ISSUE THREAD

**Issue by etienne-napoleone** [Anchor-Protocol/money-market-contracts#63]
Hello there :)

v0.3.1 of the crate is not available on crates.io.

Thanks

**Comment by bridget432** [comment]
hi @etienne-napoleone have you been able to sort this issue out?, I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> https://agora.terras.live/ To help you sort this out right away

**Comment by etienne-napoleone** [comment]
^^^
⚠️ scam

**Comment by etienne-napoleone** [comment]
Published [tag/v0.3.1](https://github.com/Anchor-Protocol/money-market-contracts/releases/tag/v0.3.1)
